system:
    debug: true
    error_reporting: -1
    offline: false
cache:
    enabled: false
    time: 15
routing:
    debug: true  # @deprecated
language:
    debug: true
whoops:
    editor: phpstorm
