# Custom routing file, all default routing files please see ./Resources/routing

home:
    pattern: /
    controller: Category
    requirements:
        page: \d+
    extra:
        layout: category
        category:
            type: article
            model: Articles
            view: Category
            ordering: article.created
            direction: DESC
            deep: true
        active:
            manimenu: home
